#!/bin/bash
####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh
####################################################################
echo "*** Building pyrap... ***"
cd $PYRAP_SVNROOT

SVN_REV=$(get_git_svnrev)
GIT_HASH=$(get_git_short_hash)
PYRAP_REV="${SVN_REV}_${GIT_HASH}"
BUILD_TARGET=$STABLE_SOFT_DIR/builds/pyrap/pyrap_r${PYRAP_REV}
mkdir -p $BUILD_TARGET
echo "Installing into $BUILD_TARGET"


ln -sfnv $BUILD_TARGET $STABLE_SOFT_DIR/builds/pyrap/pyrap-latest
git clean -f
build_command="./batchbuild-trunk.py  --prefix=$BUILD_TARGET \
    --casacore-root=$(readlink ${STABLE_SOFT_DIR}/builds/casacore/casacore-latest ) \
	--python-prefix=$BUILD_TARGET/pythonpackage install"
#--wcs-root=$WCSLIB_ROOT_DIR 
echo "$build_command" > pyrap_build_command.sh
$build_command

check_result "pyrap" "batchbuild-trunk" $?

unpack_pth_file ${BUILD_TARGET}/pythonpackage/easy-install.pth ${BUILD_TARGET}/unpacked


##make .pth paths absolute, so we can symlink to it:
#sed -i "s@^./@${BUILD_TARGET}/pythonpackage/@g" \
#	${BUILD_TARGET}/pythonpackage/easy-install.pth




