#!/bin/bash
####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR=`dirname ${0}`
BUILD_SCRIPTS_DIR=`cd $BUILD_SCRIPTS_DIR; pwd -P`
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

cd $ARCHIVE_LATEST_DIR_LINK
TARGET=`pwd -P`

SYMLINKS=$TARGET/symlinks
echo "Installing into $TARGET"

####################################################################
echo 
echo "**** Building TKP... **** "


#Create the target folder - we will install both TKP libs and trap recipes here:
cd $TKP_SVNROOT
#cd $TKP_SVNROOT/database #Database code merged into tkp
#DB_SHA=$(get_git_short_hash)
cd $TKP_SVNROOT/tkp
TKP_SHA=$(get_git_short_hash)
cd $TKP_SVNROOT/trap
TRAP_SHA=$(get_git_short_hash)
cd $TKP_SVNROOTs

TKP_TARGET=${TARGET}/tkp_${TKP_SHA}_trap-${TRAP_SHA}

echo "TKP target is $TKP_TARGET"

ln -sfn ${TKP_TARGET}/lib ${SYMLINKS}/lib/tkp
ln -sfn ${TKP_TARGET}/lib/python ${SYMLINKS}/python-packages
ln -sfn ${TKP_TARGET}/bin ${SYMLINKS}/bin/tkp

#----------------------------------------------------------------------------
#Build and install TKP libs

rm -rf $TKP_SVNROOT/tkp/build 
mkdir $TKP_SVNROOT/tkp/build
cd $TKP_SVNROOT/tkp/build

cmake_command="cmake $TKP_SVNROOT/tkp -DCMAKE_INSTALL_PREFIX=${TKP_TARGET} 
		-DTKP_DEVELOP=1 
		-DWCSLIB_ROOT_DIR=$WCSLIB_ROOT_DIR"
echo $cmake_command > cmake_command.sh
bash cmake_command.sh
check_result "tkp" "cmake" $?

make -j$LOFAR_BUILD_NJOBS
check_result "tkp" "build" $?
make install
check_result "tkp" "install" $?
 
ln -sfnv $TKP_TARGET $SYMLINKS/tkp-root #for finding the TKP recipes directory

#Symlink the catalogs into the installed folder, 
#so you can easily run a database init:
cd $SYMLINKS/tkp-root/database/catalog
ln -sfn $TKP_CATALOGS/NVSS-all_strip.csv nvss/nvss.csv
ln -sfn $TKP_CATALOGS/WENSS-all_strip.csv wenss/wenss.csv
ln -sfn $TKP_CATALOGS/VLSS-all_strip.csv vlss/vlss.csv
cd $startdir
#----------------------------------------------------------------------------
#Install trap recipes
rm -rf $TKP_SVNROOT/trap/build 
mkdir $TKP_SVNROOT/trap/build
cd $TKP_SVNROOT/trap/build
cmake_command="cmake $TKP_SVNROOT/trap -DCMAKE_INSTALL_PREFIX=${TKP_TARGET}"
echo $cmake_command > cmake_command.sh
bash cmake_command.sh
check_result "trap" "cmake" $?
make install
check_result "trap" "install" $?
cd $startdir

#Symlink the recipes folder to where it was install previously, 
#so as not to upset all the user-config files:
ln -sfnv $SYMLINKS/tkp-root/lib/python/trap/recipes $SYMLINKS/tkp-root/recipes

