#!/bin/bash
####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR=`dirname ${0}`
BUILD_SCRIPTS_DIR=`cd $BUILD_SCRIPTS_DIR; pwd -P`
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

cd $ARCHIVE_LATEST_DIR_LINK
TARGET=`pwd -P`

SYMLINKS=$TARGET/symlinks
echo "Installing into $TARGET"

####################################################################
echo 
echo "*** Building LUS... ***"

cd $LUS_SVNROOT
SVN_REV=$(get_git_svnrev)
GIT_HASH=$(get_git_short_hash)
LUS_REV="${SVN_REV}_${GIT_HASH}"

LUS_TARGET=$TARGET/lus_r${LUS_REV}
echo "LUS target is $LUS_TARGET"

rm -rf $LUS_SVNROOT/build 

bootstrap_command="./bootstrap -DLUS_INSTALL_PREFIX=${LUS_TARGET}
             -DCASACORE_ROOT_DIR=${SYMLINKS}/casacore-root 
            -DWCSLIB_ROOT_DIR=${WCSLIB_ROOT_DIR} -DWCSLIB_FORCE_BUILD=ON"

echo $bootstrap_command > bootstrap_command.sh
bash bootstrap_command.sh
check_result "LUS" "bootstrap" $?
cd $LUS_SVNROOT/build 
make anaamika -j${LOFAR_BUILD_NJOBS}
check_result "LUS" "make" $?

ln -sfn ${LUS_TARGET}/bin ${SYMLINKS}/bin/lus 
cd $startdir

