#!/bin/bash
####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh
####################################################################
echo "*** Building casacore... ***"
cd $CASACORE_SVNROOT
#cd $CASACORE_SVNROOT/casacore-1.7.0

SVN_REV=$(get_git_svnrev)
GIT_HASH=$(get_git_short_hash)
CASACORE_REV="${SVN_REV}_${GIT_HASH}"
BUILD_TARGET=$STABLE_SOFT_DIR/builds/casacore/$(date +%F-%H-%M)/casacore_r${CASACORE_REV}
#CASACORE_REV="1.7.0"
#BUILD_TARGET=$STABLE_SOFT_DIR/builds/casacore/casacore_${CASACORE_REV}

echo "Installing into $BUILD_TARGET"
mkdir -p $BUILD_TARGET
ln -sfnv $BUILD_TARGET $STABLE_SOFT_DIR/builds/casacore/casacore-latest

#Clean out any build cache:
#git clean -f

#scons -j $LOFAR_BUILD_NJOBS --prefix=$BUILD_TARGET  --enable-shared --disable-static  --data-dir=$CASA_MEASURES/data install
rm -rf build
mkdir build
cd build

cmake ..    -DCMAKE_INSTALL_PREFIX=$BUILD_TARGET \
            -DDATA_DIR=$CASA_MEASURES/data 
            

check_result "casacore" "cmake" $?
make -j $LOFAR_BUILD_NJOBS
check_result "casacore" "make" $?
make install
check_result "casacore" "make install" $?

##Copy in the measures data:
#mkdir -p $BUILD_TARGET/share/casacore/data
#cp -rf $CASA_MEASURES/data/ephemerides $CASA_MEASURES/data/geodetic \
#	$BUILD_TARGET/share/casacore/data

rm -v $BUILD_TARGET/bin/msselect #NB there is a tool of the same name in the Lofar bin





