#!/bin/bash
####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR=`dirname ${0}`
BUILD_SCRIPTS_DIR=`cd $BUILD_SCRIPTS_DIR; pwd -P`
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

cd $ARCHIVE_LATEST_DIR_LINK
TARGET=`pwd -P`

SYMLINKS=$TARGET/symlinks
echo "Installing into $TARGET"

####################################################################
echo "*** Building casarest... ***"
cd $CASAREST_SVNROOT

SVN_REV=$(get_git_svnrev)
GIT_HASH=$(get_git_short_hash)
CASAREST_REV="${SVN_REV}_${GIT_HASH}"
CASAREST_TARGET=$TARGET/casarest_r${CASAREST_REV}
#CASAREST_TARGET=$TARGET/casarest_release-1.1.1

rm -rf build/
mkdir build
cd build

cmake_command="cmake $CASAREST_SVNROOT/trunk/casarest -DCMAKE_INSTALL_PREFIX=$CASAREST_TARGET \
	-DCASACORE_ROOT_DIR=${SYMLINKS}/casacore-root \
	-DWCSLIB_ROOT_DIR=$WCSLIB_ROOT_DIR \
	-DBUILD_ALL=1"

echo $cmake_command > cmake_command.sh
bash cmake_command.sh

make -j$LOFAR_BUILD_NJOBS
check_result "casarest" "make" $?
make install
check_result "casarest" "make install" $?
ln -sfn $CASAREST_TARGET $SYMLINKS/casarest-root
ln -sfn $CASAREST_TARGET/bin $SYMLINKS/bin/casarest
ln -sfn $CASAREST_TARGET/lib $SYMLINKS/lib/casarest
