#!/bin/bash

BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

source $BUILD_SCRIPTS_DIR/CONFIG_LOCAL #defines LOFAR_BUILD_NJOBS and LOFAR_SVN_LOGIN
if [ -z "$LOFAR_BUILD_NJOBS" ]; then
    echo "*** Error: Please define the number of build processes to use (LOFAR_BUILD_NJOBS) ***"
    exit 1
fi

if [ -z "$LOFAR_SVN_LOGIN" ]; then
    echo "*** Error: Please define your username for svn.astron.nl (LOFAR_SVN_LOGIN) ***"
    exit 1
fi

#------------------------------------------------------------------------------
## Resources:

export DOWNLOAD_LOFAR_DEPS=1 ##Use wget to get the source files. Comment out if you already have them.
export UPDATE_REPOS=1
#Where to checkout the repositories
SVN_GRP_DIR=/media/RAIDA/repos
#Where to store the stable packages
LOFAR_DEPS_ROOT=$SVN_GRP_DIR
#Where to find local Lofar patches:
PATCHES_GRP_DIR=$BUILD_SCRIPTS_DIR
#Where to find the TKP catalog data:
TKP_DATA=$SVN_GRP_DIR/tkp-data

#------------------------------------------------------------------------------
## Install dirs:
# Stable software parent dir: This is where casatools, Monetdb, etc will get installed to. 
STABLE_SOFT_DIR=/opt/share/soft
# Lofar parent dir: This is where the Lofar imaging pipeline goes. 
# Builds will be archived by date and SHA hash in a subdir.
LOFAR_BUILDS_DIR=/opt/share/lofar
# Same as above, but for the TKP transients pipeline:
TKP_BUILDS_DIR=/opt/share/tkp


#------------------------------------------------------------------------------
# Stable subdirs:
WCSLIB_ROOT_DIR=$STABLE_SOFT_DIR/builds/wcslib-4.14
LOG4CPLUS_ROOT_DIR=$STABLE_SOFT_DIR/builds/log4cplus-1.0.4
PYGSL_ROOT_DIR=$STABLE_SOFT_DIR/builds/pygsl-0.9.5
PSYCOPG_ROOT_DIR=$STABLE_SOFT_DIR/builds/psycopg2-2.4.2

#------------------------------------------------------------------------------
PYRAP_SVNROOT=${SVN_GRP_DIR}/pyrap_checkout
CASACORE_SVNROOT=${SVN_GRP_DIR}/casacore_checkout/casacore
CASAREST_SVNROOT=${SVN_GRP_DIR}/casarest_checkout
CASA_MEASURES=$SVN_GRP_DIR/casa_measures

LOFAR_SRC_ROOT=${SVN_GRP_DIR}/lofar_checkout 

RSM_SRC_ROOT=${SVN_GRP_DIR}/rsm_imaging_checkout #will make build directory here.
RSM_SVNROOT=$RSM_SRC_ROOT/LOFAR #Top dir of svn checkout Has to be "LOFAR" or the build will complain.


#TKP_SVNROOT=$HOME/code/tkp-dev
TKP_SVNROOT=${SVN_GRP_DIR}/tkp-checkout
TKP_CATALOGS=${TKP_DATA}/catalogs

LUS_SVNROOT=${SVN_GRP_DIR}/LUS_repos/lofarsoft

#------------------------------------------------------------------------------
LOFAR_PYTHON_VERSION=`python -c "import sys; print sys.version[:3]"`



