#!/bin/bash
####################################################################

## Messes with the 'lofar-latest' installation in order to create a development setup.

TKP_DEV_ROOT=$HOME/code/tkp-dev

DEV_INSTALL_TARGET=/opt/lofar-dev

####################################################################
startdir=`pwd`
BUILD_SCRIPTS_DIR=`dirname ${0}`
BUILD_SCRIPTS_DIR=`cd $BUILD_SCRIPTS_DIR; pwd -P`
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

#cd $ARCHIVE_LATEST_DIR_LINK
cd $DEV_INSTALL_TARGET
TARGET=`pwd -P`

SYMLINKS=$TARGET/symlinks
echo "**** Setting up tkp-dev links from folder $TARGET ****"

####################################################################
cd $SYMLINKS/tkp-root/lib/python
mv tkp tkp-backup
mv trap trap-backup
ln -sfnv ${TKP_DEV_ROOT}/tkp/tkp tkp
ln -sfnv ${TKP_DEV_ROOT}/trap/trap trap

cd $SYMLINKS/tkp-root
mv recipes recipes-backup
ln -sfnv ${TKP_DEV_ROOT}/trap/trap/recipes recipes
mv bin bin-backup
ln -sfnv ${TKP_DEV_ROOT}/trap/trap/bin bin


cd $startdir

