#!/bin/bash
start_dir=`pwd`

echo "*** Grabbing and installing monetdb ***"
#Pull in general lofar build config:
. `dirname ${0}`/CONFIG

MDB_VER=11.11.5

mkdir -p ${LOFAR_DEPS_ROOT}/monetdb
cd ${LOFAR_DEPS_ROOT}/monetdb
if [[ -n $DOWNLOAD_LOFAR_DEPS ]]; then
  rm -rf *bz2*
  wget http://dev.monetdb.org/downloads/sources/Latest/MonetDB-${MDB_VER}.tar.bz2
  tar xvjf wcslib.tar.bz2 
fi
cd MonetDB-${MDB_VER}
TARGET=$STABLE_SOFT_DIR/builds/monetdb-${MDB_VER}
./configure --prefix=$TARGET
make install

#create symlinks
mkdir -p $STABLE_SOFT_DIR/symlinks/bin
mkdir -p $STABLE_SOFT_DIR/symlinks/lib
mkdir -p $STABLE_SOFT_DIR/symlinks/python-packages

ln -sfn $TARGET/bin $STABLE_SOFT_DIR/symlinks/bin/monetdb
ln -sfn $TARGET/lib $STABLE_SOFT_DIR/symlinks/lib/monetdb
ln -sfn $TARGET/lib/python${LOFAR_PYTHON_VERSION}/site-packages \
	$STABLE_SOFT_DIR/symlinks/python-packages/monetdb

cd $start_dir
