#!/bin/bash
#-------------------------------------------------------------------------------
#Pull in general lofar build config:
BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

#-------------------------------------------------------------------------------
# Do lofar /tkp checkouts first, so as to prompt the user for a password if necessary
# NB: note the username encoded in the URLS below.
#---------------------------------------------------------
echo "*** Checking out TKP repos ***"
mkdir -p  $TKP_SVNROOT
git clone git@github.com:transientskp/tkp.git  $TKP_SVNROOT/tkp
check_result "tkp repo" "get" $?


#Leave this till last, we don't need it until after the build.
echo "*** Checking out TKP-data ***"
mkdir -p  $TKP_DATA
git svn clone -r9 http://svn.transientskp.org/data  $TKP_DATA
echo $( cd $TKP_DATA && git svn rebase )
check_result "tkp data repo" "get" $?
#-------------------------------------------------------------------------------
