#!/bin/bash
####################################################################
BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh


TAGPATH=$1
CLONEFLAGS=""
if [[ -z "$TAGPATH" ]]; then
    TAGPATH=trunk
    CLONEFLAGS="-r28700"
fi


#------------------------------------------------------------------------------
echo "*** Checking out LOFAR ***"
REPOROOT=$LOFAR_SRC_ROOT/$TAGPATH/LOFAR
mkdir -p $REPOROOT
git svn clone --username $LOFAR_SVN_LOGIN $CLONEFLAGS https://@svn.astron.nl/LOFAR/$TAGPATH $REPOROOT
cd $REPOROOT
git svn fetch #For some reason, (https?) extra step required here.
check_result "lofar repo" "get" $?


#-------------------------------------------------------------------------------
#echo "*** Checking out LUS ***"
#mkdir -p $LUS_SVNROOT
#git svn clone -r 9750 http://usg.lofar.org/svn/code/trunk $LUS_SVNROOT
#check_result "LUS repo" "get" $?
#-------------------------------------------------------------------------------

echo "*** LOFAR svn group repos checked out successfully *** "

