#!/bin/bash
start_dir=`pwd`

echo "*** Grabbing and installing wcslib ***"
#Pull in general lofar build config:
. `dirname ${0}`/CONFIG

mkdir -p ${LOFAR_DEPS_ROOT}/wcslib
cd ${LOFAR_DEPS_ROOT}/wcslib
if [[ -n $DOWNLOAD_LOFAR_DEPS ]]; then
  rm -rf *bz2*
  wget ftp://ftp.atnf.csiro.au/pub/software/wcslib/wcslib.tar.bz2 .
  bunzip2 -f wcslib.tar.bz2 

fi
tar xf wcslib.tar
cd wcslib-4.14
./configure --prefix=$WCSLIB_ROOT_DIR
make install

#create symlink so libpath gets picked up by the init script
mkdir -p $STABLE_SOFT_DIR/symlinks/lib/wcslib
ln -sfn $WCSLIB_ROOT_DIR/lib $STABLE_SOFT_DIR/symlinks/lib/wcslib

cd $start_dir
