#!/bin/bash
start_dir=`pwd`

echo "*** Grabbing and installing monetdb ***"
#Pull in general lofar build config:
. `dirname ${0}`/CONFIG

MDB_VER=11.13.3

mkdir -p ${LOFAR_DEPS_ROOT}/monetdb
cd ${LOFAR_DEPS_ROOT}/monetdb
if [[ -n $DOWNLOAD_LOFAR_DEPS ]]; then
	echo "*** Downloading monetdb... ***"
  rm -rf *bz2*
  wget http://dev.monetdb.org/downloads/sources/Oct2012/MonetDB-${MDB_VER}.tar.bz2
#  wget http://dev.monetdb.org/downloads/sources/Oct2012/python-monetdb-${MDB_VER}.tar.bz2
  tar xvjf MonetDB-${MDB_VER}.tar.bz2
fi
cd MonetDB-${MDB_VER}
TARGET=$STABLE_SOFT_DIR/builds/monetdb-${MDB_VER}
./configure --prefix=$TARGET
make install

#create symlinks
mkdir -p $STABLE_SOFT_DIR/symlinks/bin
mkdir -p $STABLE_SOFT_DIR/symlinks/lib

## NB Don't use the packaged version of monetdb (as of 12-09-14). Use pip to install the latest `python-monetdb' package from pypi.
#mkdir -p $STABLE_SOFT_DIR/symlinks/python-packages 

ln -sfn $TARGET/bin $STABLE_SOFT_DIR/symlinks/bin/monetdb
ln -sfn $TARGET/lib $STABLE_SOFT_DIR/symlinks/lib/monetdb
ln -sfn $TARGET/lib/python${LOFAR_PYTHON_VERSION}/site-packages \
	$STABLE_SOFT_DIR/symlinks/python-packages/monetdb

cd $start_dir
