#!/bin/bash
####################################################################
BUILD_SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source $BUILD_SCRIPTS_DIR/CONFIG
source $BUILD_SCRIPTS_DIR/utils.sh

#------------------------------------------------------------------------------
echo "*** Checking out LOFAR ***"
mkdir -p $LOFAR_SVNROOT 
git svn clone --username $LOFAR_SVN_LOGIN -r22500 https://@svn.astron.nl/LOFAR/trunk $LOFAR_SVNROOT 
cd $LOFAR_SVNROOT
git svn fetch #For some reason, (https?) extra step required here.
check_result "lofar repo" "get" $?


#-------------------------------------------------------------------------------
#echo "*** Checking out LUS ***"
#mkdir -p $LUS_SVNROOT
#git svn clone -r 9750 http://usg.lofar.org/svn/code/trunk $LUS_SVNROOT
#check_result "LUS repo" "get" $?
#-------------------------------------------------------------------------------

echo "*** LOFAR svn group repos checked out successfully *** "

