#!/bin/bash
start_dir=`pwd`

echo "*** Grabbing and installing psycopg ***"
#Pull in general lofar build config:
. `dirname ${0}`/CONFIG

PSYCO_VER=2.4.6

mkdir -p ${LOFAR_DEPS_ROOT}/psycopg
cd ${LOFAR_DEPS_ROOT}/psycopg
if [[ -n $DOWNLOAD_LOFAR_DEPS ]]; then
  wget http://initd.org/psycopg/tarballs/PSYCOPG-2-4/psycopg2-$PSYCO_VER.tar.gz .
fi
rm -rf psycopg2-$PSYCO_VER
tar zxf psycopg2-$PSYCO_VER.tar.gz
cd psycopg2-$PSYCO_VER
python setup.py install --prefix=$PSYCOPG_ROOT_DIR

#symlinks

mkdir -p $STABLE_SOFT_DIR/symlinks/python-packages
ln -sfn $PSYCOPG_ROOT_DIR/lib/python${LOFAR_PYTHON_VERSION}/site-packages ${STABLE_SOFT_DIR}/symlinks/python-packages/psycopg

cd $start_dir
